version: '3'

includes:
  claude:
    taskfile: .claude
    optional: true
    flatten: true

tasks:
  default:
    cmds:
      - cmd: task --list-all
    silent: true

  add:
    dir: ./
    cmds:
      - cmd: git submodule add -b main https://github.com/brianclaridge/.claude.git
      - cmd: git submodule update --init --recursive --remote
